-- Estrutura esperada da tabela logs (NÃO CRIAR - APENAS DOCUMENTAÇÃO)
-- A tabela deve existir previamente no banco de dados
--
-- Estrutura esperada:
-- logs (
--     id UUID PRIMARY KEY, 
--     service_time FLOAT NOT NULL,
--     room_ids INTEGER[] NOT NULL,
--     success_count INTEGER NOT NULL,
--     total_count INTEGER NOT NULL,
--     created_at TIMESTAMP WITH TIME ZONE
-- )